### ISSUE TITLE
Improve Teaser sign tracker

### ISSUE THREAD

**Issue by chezzdev** [mapbox/vision-ios-examples#140]
@chezzdev commented on [Sun Apr 19 2020](https://github.com/mapbox/mapbox-vision/issues/2474)

## Description
In the Teaser, we have a very simple tracker that depends on the frequency of sign updates.
It works ok for demos but has some downsides for real-time rides.

The proposal is to make elements in the tracker to retire based on the timed updates, not the external updates.

## Goal
Improve sign tracker in Teaser.

## Steps
- [ ] Rewise element retirement logic
- [ ] Use internal timer
- [ ] Tested and acceptance criteria is matched (result matches the goal)

---

### Issue checklist
- [x] Set Epic, Estimation, Release, Labels
